# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'rpkn'
tagline:          'Robin Karlsson, Webbprogrammerare'
description:      'Robin Karlsson'
baseurl:          / 

author:
  name:           'Robin Karlsson'
  url:            https://twitter.com/ropkn

paginate:         5

github:	
  repo: https://github.com/rk222ev          
